name: LitGit build

on:
  push:
    branches:
      - master
      - develop
      - feature/actions
jobs:
  build:
    env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build Linux
      run: ./build.sh
      if: matrix.os == 'ubuntu-latest'
    - name: Build Windows
      run: .\build.ps1
      if: matrix.os == 'windows-latest'
    - name: Run tests
      run: ./test.sh
      working-directory: Test
      shell: bash
    - name: Deploy Nuget Package
      run: ./tools/nuget push ./output/*.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
      shell: bash
      if: matrix.os == 'windows-latest' && github.event_name != 'pull_request'
